# Generated by Django 5.0.3 on 2024-03-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.IntegerField(default=1),
        ),
    ]
